# Generated by Django 5.1.7 on 2025-04-16 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rota', '0003_alter_shift_options_alter_shiftswaprequest_shift_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='availability',
            options={'verbose_name_plural': 'Availabilities'},
        ),
        migrations.AlterModelOptions(
            name='invitetoken',
            options={'verbose_name': 'Invite Token', 'verbose_name_plural': 'Invite Tokens'},
        ),
        migrations.AlterModelOptions(
            name='notificationreadstatus',
            options={'verbose_name': 'Notification Read Status', 'verbose_name_plural': 'Notification Read Statuses'},
        ),
        migrations.AlterModelOptions(
            name='shiftrolerequirement',
            options={'verbose_name': 'Shift Role Requirement', 'verbose_name_plural': 'Shift Role Requirements'},
        ),
        migrations.AlterModelOptions(
            name='shiftswaprequest',
            options={'verbose_name': 'Shift Swap Request', 'verbose_name_plural': 'Shift Swap Requests'},
        ),
        migrations.AlterModelOptions(
            name='shifttemplate',
            options={'verbose_name': 'Shift Template', 'verbose_name_plural': 'Shift Templates'},
        ),
        migrations.AddField(
            model_name='invitetoken',
            name='role',
            field=models.CharField(choices=[('manager', 'Manager'), ('employee', 'Employee')], default='employee', max_length=20),
        ),
    ]
