name: Generate OpenAPI Docs

on:
  push:
    branches:
      - main  # change if your branch is different

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r backend/requirements.txt
        pip install drf-spectacular

    - name: Generate schema.yaml
      run: |
        cd backend
        python manage.py spectacular --file ../docs/schema.yaml

    - name: Commit schema.yaml
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git add docs/schema.yaml
        git commit -m "Update API schema [auto]" || echo "No changes to commit"
        git push
